version: '3.8'

services:

  short_link_api:
    image: short_link_service:latest
    container_name: short_link_api
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgres://${DB_USER}:${DB_PASSWORD}@short_link_db:5432/${DB_DATABASE}?sslmode=disable
    depends_on:
      short_link_db:
        condition: service_healthy
    networks:
      - short_link_network

  short_link_db:
    image: postgres:12-alpine
    container_name: short_link_db
    ports:
      - "8001:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - short_link_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  short_link_network:
    name: short_link_network
